#!/usr/bin/env python3
"""
Generate UAE-style synthetic KYB document packs (PDF) for demo/testing.

This version intentionally does NOT include machine-only hints such as:
- DOC_TYPE: ...
- CITATION_ID / CITATION_ANCHOR

That keeps PDFs closer to real-world documents. Document classification and citation
links should be generated by the API from extracted text + blob/document ids.

Documents per case:
- Trade License
- MOA / AOA
- Board Resolution
- IDs (UBO / Authorized Signatory)
- Bank Letter
- VAT / TRN Certificate
- Financial Statements (Balance Sheet + P&L simplified)

Creates 10 different cases with realistic variations (expiry, audit status, profits/losses, conflicts).
All content is synthetic and non-PII.

Output:
  synthetic_cases/
    case_01/
      trade_license.pdf
      moa_aoa.pdf
      board_resolution.pdf
      ids.pdf
      bank_letter.pdf
      vat_trn.pdf
      financial_statements.pdf
      manifest.json
    ...
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from datetime import date, timedelta
import random
from typing import Dict, List, Tuple

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm


def _draw_paragraph_pdf(
    out_path: Path,
    title: str,
    lines: List[str],
    subtitle: str | None = None,
    footer: str | None = None,
) -> None:
    """Render a simple 'document-like' PDF with a header and body lines."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(out_path), pagesize=A4)
    width, height = A4

    y = height - 22 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(20 * mm, y, title)
    y -= 8 * mm

    if subtitle:
        c.setFont("Helvetica", 10)
        for ln in subtitle.splitlines():
            c.drawString(20 * mm, y, ln)
            y -= 5 * mm
        y -= 3 * mm

    c.setFont("Helvetica", 10)
    wrap_chars = 110

    for raw in lines:
        # wrap
        chunks = [raw[i:i+wrap_chars] for i in range(0, len(raw), wrap_chars)] or [""]
        for ln in chunks:
            if y < 25 * mm:
                c.showPage()
                y = height - 22 * mm
                c.setFont("Helvetica", 10)
            c.drawString(20 * mm, y, ln)
            y -= 5 * mm
        y -= 1 * mm

    if footer:
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(20 * mm, 15 * mm, footer)

    c.showPage()
    c.save()


def _rand_trn(rng: random.Random) -> str:
    # UAE TRN commonly represented as 15 digits.
    return "".join(str(rng.randint(0, 9)) for _ in range(15))


def _rand_license_no(rng: random.Random) -> str:
    # Synthetic Dubai-style format
    return f"TL-{rng.randint(2022, 2026)}-{rng.randint(100000, 999999)}"


def _rand_cr_no(rng: random.Random) -> str:
    return f"CR-{rng.randint(1000000, 9999999)}"


def _rand_iban(rng: random.Random) -> str:
    # Synthetic UAE IBAN-like (not real)
    return "AE" + "".join(str(rng.randint(0, 9)) for _ in range(21))


def _fmt(d: date) -> str:
    return d.isoformat()


@dataclass
class CaseSpec:
    case_id: str
    company_name: str
    legal_name: str
    jurisdiction: str
    issuing_authority: str
    license_no: str
    reg_no: str
    issue_date: date
    expiry_date: date
    trn: str
    bank_name: str
    iban: str
    fiscal_year: int
    revenue: int
    net_profit_loss: int
    total_assets: int
    total_liabilities: int
    audit_status: str
    ubo_name: str
    ubo_nationality: str
    ubo_id_no: str
    ubo_dob: date
    ubo_ownership_pct: int
    signatory_name: str
    signatory_role: str
    flags: Dict[str, str]


def build_cases(n: int = 10, seed: int = 20260304) -> List[CaseSpec]:
    rng = random.Random(seed)
    base_issue = date(2026, 3, 1)

    companies = [
        ("Desert Pearl Trading LLC", "Desert Pearl Trading L.L.C."),
        ("Blue Dune Logistics LLC", "Blue Dune Logistics L.L.C."),
        ("Palm Bridge Foods LLC", "Palm Bridge Foods L.L.C."),
        ("Skyline Tech Services LLC", "Skyline Tech Services L.L.C."),
        ("Marina Gulf Supplies LLC", "Marina Gulf Supplies L.L.C."),
        ("Oasis Prime Consulting LLC", "Oasis Prime Consulting L.L.C."),
        ("Falcon Crest Retail LLC", "Falcon Crest Retail L.L.C."),
        ("Emirates Star Manufacturing LLC", "Emirates Star Manufacturing L.L.C."),
        ("Harbor Point Ventures LLC", "Harbor Point Ventures L.L.C."),
        ("Crescent Bay Hospitality LLC", "Crescent Bay Hospitality L.L.C."),
    ]

    scenarios = [
        {"scenario": "baseline_good", "notes": "Audited, profitable, valid license"},
        {"scenario": "expired_license", "notes": "Trade license expired"},
        {"scenario": "unaudited_financials", "notes": "Audit status unaudited"},
        {"scenario": "net_loss", "notes": "Negative profitability"},
        {"scenario": "liabilities_exceed_assets", "notes": "Solvency risk"},
        {"scenario": "conflicting_trn", "notes": "TRN mismatch between Trade License and VAT cert"},
        {"scenario": "missing_board_resolution_fields", "notes": "Board resolution incomplete"},
        {"scenario": "multiple_ubos", "notes": "Two UBOs listed in IDs doc"},
        {"scenario": "low_confidence_keywords", "notes": "Sparse keywords to test classification confidence"},
        {"scenario": "high_revenue_high_assets", "notes": "Large scale audited company"},
    ]

    cases: List[CaseSpec] = []
    for i in range(n):
        company_name, legal_name = companies[i % len(companies)]
        flags = scenarios[i % len(scenarios)]

        issue_date = base_issue - timedelta(days=rng.randint(0, 45))
        expiry_date = issue_date + timedelta(days=365)
        if flags["scenario"] == "expired_license":
            expiry_date = base_issue - timedelta(days=10)

        fiscal_year = 2025 if i < 7 else 2024

        revenue = rng.randint(800_000, 4_500_000)
        net = rng.randint(50_000, 550_000)
        assets = rng.randint(900_000, 6_000_000)
        liab = rng.randint(100_000, 2_500_000)
        audit_status = "AUDITED"

        if flags["scenario"] == "unaudited_financials":
            audit_status = "UNAUDITED"
        if flags["scenario"] == "net_loss":
            net = -rng.randint(20_000, 400_000)
        if flags["scenario"] == "liabilities_exceed_assets":
            assets = rng.randint(500_000, 1_500_000)
            liab = assets + rng.randint(50_000, 900_000)
        if flags["scenario"] == "high_revenue_high_assets":
            revenue = rng.randint(12_000_000, 45_000_000)
            net = rng.randint(900_000, 8_000_000)
            assets = rng.randint(20_000_000, 140_000_000)
            liab = rng.randint(2_000_000, 40_000_000)
            audit_status = "AUDITED"

        trn = _rand_trn(rng)
        license_no = _rand_license_no(rng)
        reg_no = _rand_cr_no(rng)

        ubo_name = ["Aarav Synthetic", "Noor Synthetic", "Zain Synthetic", "Maya Synthetic"][i % 4]
        ubo_nat = ["IN", "AE", "PK", "GB"][i % 4]
        ubo_id = f"P{rng.randint(1000000, 9999999)}"
        ubo_dob = date(1985 + (i % 10), 5, 12)
        ubo_pct = 75 if flags["scenario"] != "multiple_ubos" else 60

        sign_name = ["Ravi Demo", "Sara Demo", "Omar Demo", "Leena Demo"][i % 4]
        sign_role = "Authorized Signatory"

        bank_name = ["Emirates NBD", "Mashreq Bank", "ADCB", "FAB"][i % 4]
        iban = _rand_iban(rng)

        cases.append(
            CaseSpec(
                case_id=f"case_{i+1:02d}",
                company_name=company_name,
                legal_name=legal_name,
                jurisdiction="Dubai, UAE",
                issuing_authority="Dubai Economy & Tourism (DET)",
                license_no=license_no,
                reg_no=reg_no,
                issue_date=issue_date,
                expiry_date=expiry_date,
                trn=trn,
                bank_name=bank_name,
                iban=iban,
                fiscal_year=fiscal_year,
                revenue=revenue,
                net_profit_loss=net,
                total_assets=assets,
                total_liabilities=liab,
                audit_status=audit_status,
                ubo_name=ubo_name,
                ubo_nationality=ubo_nat,
                ubo_id_no=ubo_id,
                ubo_dob=ubo_dob,
                ubo_ownership_pct=ubo_pct,
                signatory_name=sign_name,
                signatory_role=sign_role,
                flags=flags,
            )
        )

    return cases


def generate_case_docs(out_dir: Path, c: CaseSpec) -> None:
    case_dir = out_dir / c.case_id
    case_dir.mkdir(parents=True, exist_ok=True)

    # Introduce TRN mismatch in Trade License (for conflict scenario)
    tl_trn = c.trn
    if c.flags["scenario"] == "conflicting_trn":
        tl_trn = tl_trn[:-1] + ("0" if tl_trn[-1] != "0" else "1")

    # Trade License
    if c.flags["scenario"] == "low_confidence_keywords":
        tl_title = "Business License"
        tl_lines = [
            f"Company: {c.legal_name}",
            f"License Number: {c.license_no}",
            f"Issued: {_fmt(c.issue_date)}",
            f"Expires: {_fmt(c.expiry_date)}",
            f"TRN: {tl_trn}",
            f"Jurisdiction: {c.jurisdiction}",
        ]
    else:
        tl_title = "UAE Trade License"
        tl_lines = [
            "Dubai Economy & Tourism (DET)",
            "TRADE LICENSE / COMMERCIAL LICENSE",
            f"Legal Name: {c.legal_name}",
            f"Trade Name: {c.company_name}",
            f"License No: {c.license_no}",
            f"Commercial Registration (CR): {c.reg_no}",
            f"Jurisdiction: {c.jurisdiction}",
            f"Issuing Authority: {c.issuing_authority}",
            f"Issue Date: {_fmt(c.issue_date)}",
            f"Expiry Date: {_fmt(c.expiry_date)}",
            f"Tax Registration Number (TRN): {tl_trn}",
            "Activity: General Trading",
        ]
    _draw_paragraph_pdf(
        case_dir / "trade_license.pdf",
        tl_title,
        tl_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # MOA / AOA
    moa_lines = [
        "MEMORANDUM AND ARTICLES OF ASSOCIATION",
        f"Company (Legal Name): {c.legal_name}",
        f"Commercial Registration (CR): {c.reg_no}",
        "Legal Form: Limited Liability Company (LLC)",
        "Registered Address: Business Bay, Dubai, UAE",
        "Share Capital: AED 300,000",
        "Objects: General trading and related activities",
    ]
    _draw_paragraph_pdf(
        case_dir / "moa_aoa.pdf",
        "Memorandum / Articles of Association (MOA/AOA)",
        moa_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # Board Resolution
    if c.flags["scenario"] == "missing_board_resolution_fields":
        br_lines = [
            "BOARD RESOLUTION",
            f"Company: {c.legal_name}",
            "Date: 2026-02-20",
            "RESOLVED THAT the Company shall proceed with KYB submission and related documentation.",
            "(Intentionally missing signatory details for demo exception.)",
        ]
    else:
        br_lines = [
            "BOARD RESOLUTION",
            f"Company: {c.legal_name}",
            "Meeting Date: 2026-02-20",
            "RESOLVED THAT the following person is appointed as Authorized Signatory:",
            f"Name: {c.signatory_name}",
            f"Role: {c.signatory_role}",
            "Authority: Open and operate bank accounts; sign agreements; submit KYB documentation.",
        ]
    _draw_paragraph_pdf(
        case_dir / "board_resolution.pdf",
        "Board Resolution",
        br_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # IDs (UBO / Signatory)
    ids_lines = [
        "IDENTIFICATION DOCUMENTS SUMMARY",
        "Ultimate Beneficial Owner (UBO)",
        f"Name: {c.ubo_name}",
        f"Nationality: {c.ubo_nationality}",
        f"Date of Birth: {_fmt(c.ubo_dob)}",
        f"Passport No: {c.ubo_id_no}",
        f"Ownership: {c.ubo_ownership_pct}%",
        " ",
        "Authorized Signatory",
        f"Name: {c.signatory_name}",
        f"Role: {c.signatory_role}",
        f"Emirates ID (Synthetic): EID{random.randint(100000000000, 999999999999)}",
    ]
    if c.flags["scenario"] == "multiple_ubos":
        ids_lines.extend([
            " ",
            "Additional UBO",
            "Name: Hana Synthetic",
            "Nationality: AE",
            "Date of Birth: 1991-11-03",
            f"Passport No: P{random.randint(1000000, 9999999)}",
            "Ownership: 40%",
        ])
    _draw_paragraph_pdf(
        case_dir / "ids.pdf",
        "IDs (UBO / Authorized Signatory)",
        ids_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # Bank Letter
    bank_lines = [
        "To Whom It May Concern,",
        f"This is to confirm that {c.legal_name} maintains an active account with {c.bank_name}.",
        f"Account Holder: {c.legal_name}",
        f"IBAN: {c.iban}",
        "Account Status: ACTIVE",
        "Letter Date: 2026-02-25",
        "Sincerely,",
        f"{c.bank_name} - Corporate Banking (Synthetic)",
    ]
    _draw_paragraph_pdf(
        case_dir / "bank_letter.pdf",
        "Bank Confirmation Letter",
        bank_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # VAT / TRN Certificate (authoritative TRN)
    vat_lines = [
        "FEDERAL TAX AUTHORITY (FTA)",
        "VAT / TAX REGISTRATION CERTIFICATE",
        f"Taxable Person: {c.legal_name}",
        f"Tax Registration Number (TRN): {c.trn}",
        "VAT Effective Date: 2023-01-01",
        "This certificate is issued for demonstration purposes only.",
    ]
    _draw_paragraph_pdf(
        case_dir / "vat_trn.pdf",
        "VAT / TRN Certificate",
        vat_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # Financial Statements (Balance Sheet + P&L simplified)
    fs_lines = [
        "FINANCIAL STATEMENTS (SIMPLIFIED)",
        f"Period: FY{c.fiscal_year}",
        " ",
        "Profit and Loss (P&L)",
        f"Revenue: AED {c.revenue:,}",
        f"Net Profit/Loss: AED {c.net_profit_loss:,}",
        " ",
        "Balance Sheet (Statement of Financial Position)",
        f"Total Assets: AED {c.total_assets:,}",
        f"Total Liabilities: AED {c.total_liabilities:,}",
        " ",
        f"Audit Status: {c.audit_status}",
    ]
    _draw_paragraph_pdf(
        case_dir / "financial_statements.pdf",
        "Financial Statements (Balance Sheet + P&L)",
        fs_lines,
        subtitle="Synthetic UAE-style document for demo purposes only.",
        footer="Generated by generate_synthetic_docs_uae_cases_v2.py",
    )

    # Manifest
    import json as _json
    manifest = {
        "case_id": c.case_id,
        "company_name": c.company_name,
        "legal_name": c.legal_name,
        "scenario": c.flags.get("scenario"),
        "notes": c.flags.get("notes"),
        "expected_risk_signals": {
            "license_expired": c.expiry_date < date.today(),
            "unaudited": c.audit_status != "AUDITED",
            "net_loss": c.net_profit_loss < 0,
            "liabilities_gt_assets": c.total_liabilities > c.total_assets,
            "conflicting_trn": c.flags.get("scenario") == "conflicting_trn",
            "board_resolution_incomplete": c.flags.get("scenario") == "missing_board_resolution_fields",
            "multiple_ubos": c.flags.get("scenario") == "multiple_ubos",
        },
        "documents": [
            "trade_license.pdf",
            "moa_aoa.pdf",
            "board_resolution.pdf",
            "ids.pdf",
            "bank_letter.pdf",
            "vat_trn.pdf",
            "financial_statements.pdf",
        ],
    }
    (case_dir / "manifest.json").write_text(_json.dumps(manifest, indent=2), encoding="utf-8")


def main() -> None:
    out_dir = Path("synthetic_cases")
    cases = build_cases(n=10, seed=20260304)
    for c in cases:
        generate_case_docs(out_dir, c)
    print(f"Generated {len(cases)} cases in: {out_dir.resolve()}")
    print("Example: synthetic_cases/case_01/trade_license.pdf")


if __name__ == "__main__":
    main()
